### ISSUE TITLE
Invalid path for Logical Volume

### ISSUE THREAD

**Issue by eurodomenii** [LINBIT/thin-send-recv#1]
Congrats for this beautiful piece of software,  that fixes the long overdue https://linux-lvm.redhat.narkive.com/8FJ4Bo6M/lvm-send-receive-support#post2

This could be a fresh alternative to ZFS, for the featured Proxmox storage replication 
https://forum.proxmox.com/threads/supported-storage-types-for-storage-replication.88396/ , since ZFS is not welcomed in Linux https://arstechnica.com/gadgets/2020/01/linus-torvalds-zfs-statements-arent-right-heres-the-straight-dope/ and XFS is off the table for the moment https://marc.info/?l=linux-xfs&m=161990684619262&w=2

Following your example
`thin_send ssd_vg/CentOS7.6 ssd_vg/li0 | ssh root@target-machine thin_recv kubuntu-vg/li0`

I get

```
root@melania:~# thin_send vgnvme1/snap_vm-894-disk-0_snap1 vgnvme1/snap_vm-894-disk-0_snap2 | ssh max thin_recv vgnvme1/vm-894-disk-0    "vgnvme1/snap_vm-894-disk-0_snap1 vgnvme1/snap_vm-894-disk-0_snap2": Invalid path for Logical Volume.
failed to parse lvs output -1 cmdline=lvs --noheadings -o vg_name,lv_name,pool_lv,lv_dm_path,thin_id vgnvme1/snap_vm-894-disk-0_snap1 vgnvme1/snap_vm-894-disk-0_snap2

```
I guess this sends “vgnvme1/snap_vm-894-disk-0_snap1 vgnvme1/snap_vm-894-disk-0_snap2” as a single  volume|snapshot

For debugging purposes, I ran the following “dummy” commands:

```
root@melania:~# lvs --noheadings -o vg_name,lv_name,pool_lv,lv_dm_path,thin_id vgnvme1/snap_vm-894-disk-0_snap1
  vgnvme1 snap_vm-894-disk-0_snap1 lvnvme1 /dev/mapper/vgnvme1-snap_vm--894--disk--0_snap1  231

root@melania:~# lvs --noheadings -o vg_name,lv_name,pool_lv,lv_dm_path,thin_id vgnvme1/snap_vm-894-disk-0_snap2
  vgnvme1 snap_vm-894-disk-0_snap2 lvnvme1 /dev/mapper/vgnvme1-snap_vm--894--disk--0_snap2  232

root@melania:~# thin_send -t vgnvme1/snap_vm-894-disk-0_snap1 | ssh max thin_recv vgnvme1/vm-894-disk-0                               
failed to open snap2: No such file or directory

root@melania:~# thin_send -t vgnvme1/snap_vm-894-disk-0_snap1_dummy | ssh max thin_recv vgnvme1/vm-894-disk-0
  Failed to find logical volume "vgnvme1/snap_vm-894-disk-0_snap1_dummy"
failed to parse lvs output -1 cmdline=lvs --noheadings -o vg_name,lv_name,pool_lv,lv_dm_path,thin_id vgnvme1/snap_vm-894-disk-0_snap1_dummy

```
I got a sneak peak of the relevant code from https://github.com/LINBIT/thin-send-recv/blob/master/thin_send_recv.c:

```
void get_snap_info(const char *snap_name, struct snap_info *info) from 
checked_asprintf(&cmdline, "lvs --noheadings -o vg_name,lv_name,pool_lv,lv_dm_path,thin_id %s", snap_name);

int main(int argc, char **argv)
if (optind == argc - 1)
			thin_send_vol(argv[optind], fileno(stdout));
		else if (optind == argc - 2)
			thin_send_diff(argv[optind], argv[optind + 1], fileno(stdout));

```
Here are my settings:

```
--- Logical volume ---
  LV Path                /dev/vgnvme1/vm-894-disk-0
  LV Name                vm-894-disk-0
  VG Name                vgnvme1
  LV UUID                eHR3wM-nN98-iHfu-6jbd-Kcsv-RqIu-qqjsvw
  LV Write Access        read/write
  LV Creation host, time melania, 2021-05-04 11:01:33 +0300
  LV Pool name           lvnvme1
  LV Status              available
  # open                 1
  LV Size                <20.20 GiB
  Mapped size            53.41%
  Current LE             5171
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     256
  Block device           253:33

  --- Logical volume ---
  LV Path                /dev/vgnvme1/snap_vm-894-disk-0_snap1
  LV Name                snap_vm-894-disk-0_snap1
  VG Name                vgnvme1
  LV UUID                lyAsz8-ZI8N-mkjl-6LG3-F5E3-WoHb-yi4tuS
  LV Write Access        read only
  LV Creation host, time melania, 2021-05-04 11:04:30 +0300
  LV Pool name           lvnvme1
  LV Thin origin name    vm-894-disk-0
  LV Status              NOT available
  LV Size                <20.20 GiB
  Current LE             5171
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto

  --- Logical volume ---
  LV Path                /dev/vgnvme1/snap_vm-894-disk-0_snap2
  LV Name                snap_vm-894-disk-0_snap2
  VG Name                vgnvme1
  LV UUID                jEfqdD-nwcJ-del3-EbEs-kYd6-bq18-ua8vSl
  LV Write Access        read only
  LV Creation host, time melania, 2021-05-04 11:05:57 +0300
  LV Pool name           lvnvme1
  LV Thin origin name    vm-894-disk-0
  LV Status              NOT available
  LV Size                <20.20 GiB
  Current LE             5171
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto

```

Thank you!

**Comment by rck** [comment]
If you want to use replicated storage in Proxmox you could use DRBD/LINSTOR: https://github.com/linbit/linstor-proxmox

@Philipp-Reisner will take care of the rest.

**Comment by Philipp-Reisner** [comment]
> Following your example
> `thin_send ssd_vg/CentOS7.6 ssd_vg/li0 | ssh root@target-machine thin_recv kubuntu-vg/li0`
> 
> I get
> 
> ```
> root@melania:~# thin_send vgnvme1/snap_vm-894-disk-0_snap1 vgnvme1/snap_vm-894-disk-0_snap2 | ssh max thin_recv vgnvme1/vm-894-disk-0    "vgnvme1/snap_vm-894-disk-0_snap1 vgnvme1/snap_vm-894-disk-0_snap2": Invalid path for Logical Volume.
> failed to parse lvs output -1 cmdline=lvs --noheadings -o vg_name,lv_name,pool_lv,lv_dm_path,thin_id vgnvme1/snap_vm-894-disk-0_snap1 vgnvme1/snap_vm-894-disk-0_snap2
> ```
> 
> I guess this sends “vgnvme1/snap_vm-894-disk-0_snap1 vgnvme1/snap_vm-894-disk-0_snap2” as a single volume|snapshot

What? How do you manage that "vgnvme1/snap_vm-894-disk-0_snap1 vgnvme1/snap_vm-894-disk-0_snap2" is passed as a single argument to the program?
The snapshot names need to be two arguments. Are you using an exotic shell?

PS: The other problem you might run into is, that all snapshots needs to be activated. I will commit a change later, that lifts that requirement. (For our use-case with LINSTOR, we need the snapshots active, so I did not noticed that before...)

**Comment by eurodomenii** [comment]
> Are you using an exotic shell?

No. I was connecting  to the Proxmox node from Putty. After your reply, I've ssh into the proxmox node from a Debian 10.9 server, buth with the same output "Invalid path for Logical Volume"

The proxmox node is 
```
root@melania:/# pveversion
pve-manager/6.4-4/337d6701 (running kernel: 5.4.106-1-pve)
```

**Comment by Philipp-Reisner** [comment]
Hmm, please make sure that there is no special character between the two arguments for the snapshots. Maybe something that came with copy-n-paste.

When I execute the same command on my machine (Ubuntu 20.04) it looks like that:
```
./thin_send --allow-tty vgnvme1/snap_vm-894-disk-0_snap1 vgnvme1/snap_vm-894-disk-0_snap2
  Volume group "vgnvme1" not found
  Cannot process volume group vgnvme1
failed to parse lvs output -1 cmdline=lvs --noheadings -o vg_name,lv_name,pool_lv,lv_dm_path,thin_id,attr vgnvme1/snap_vm-894-disk-0_snap1
```
It is expected that there is no vgnvme1 on my machine. But the relevant thing is that the two arguments get seperated by my bash and passed as two arguments to the program (instead of one containing both with seperated by a space). You can see that at the end of the "failed to parse..." line.

This all looks like you are trying to doing tricks with shell quoting that do not do what you expect.

**Comment by eurodomenii** [comment]
> Hmm, please make sure that there is no special character between the two arguments for the snapshots. Maybe something that came with copy-n-paste.

Your intuition was excellent! Even though I wasn’t using an exotic shell,  my workflow led me to an unexpected output.

Being out of office, I was connecting to my desktop via Windows Remote Desktop through a ssh tunnel, and from there via putty to the Proxmox node.

To be even more confusing, getting back to office, I reran the commands from shell history,  perpetuating the mistake. Only new attempts worked, with correct copy-n-paste via direct putty connection.

The offending invisible characters codes were 302 and 240.

```
root@melania:~# echo thin_send --allow-tty vgnvme1/snap_vm-994-disk-0_snap1 vgnvme1/snap_vm-994-disk-0_snap2 | od  -c
0000000   t   h   i   n   _   s   e   n   d       -   -   a   l   l   o
0000020   w   -   t   t   y       v   g   n   v   m   e   1   /   s   n
0000040   a   p   _   v   m   -   9   9   4   -   d   i   s   k   -   0
0000060   _   s   n   a   p   1 302 240   v   g   n   v   m   e   1   /
0000100   s   n   a   p   _   v   m   -   9   9   4   -   d   i   s   k
0000120   -   0   _   s   n   a   p   2  \n
0000131

```
Sorry for the noise. However, after posting my configuration, you’ve noticed 

> PS: The other problem you might run into is, that all snapshots needs to be activated. I will commit a change later, that lifts that requirement.


At least one good thing came out of this  https://github.com/LINBIT/thin-send-recv/issues/2  :-)
