### ISSUE TITLE
Allow send even for inactive snapshots

### ISSUE THREAD

**Issue by eurodomenii** [LINBIT/thin-send-recv#2]
Allow send even for inactive snapshots, following @Philipp-Reisner observation from:

https://github.com/LINBIT/thin-send-recv/issues/1#issuecomment-831960053

> PS: The other problem you might run into is, that all snapshots needs to be activated. I will commit a change later, that lifts that requirement. 

For instance, if _vgnvme1/snap_vm-894-disk-0_snap2_ is not activated, it fails 

```
root@melania:~# thin_send vgnvme1/snap_vm-894-disk-0_snap1 vgnvme1/snap_vm-894-disk-0_snap2 | ssh max thin_recv vgnvme1/vm-894-disk-0

failed to open snap2: No such file or directory

```
For testing purpose, the following command 

`lvchange -ay -Ky vgnvme1/snap_vm-894-disk-0_snap2`

changes _LV Status_ from _"NOT available"_, to _"available"_

**Comment by Philipp-Reisner** [comment]
fixed by da66ef7578a6663096d5b0c45bab4e0d02301edd
